from __future__ import annotations


def google_md_text() -> str:
    return (
        "\n".join(
            [
                "# Google OAuth Setup (Freeclaw)",
                "",
                "This guide configures Google OAuth directly inside Freeclaw.",
                "No external gauth server is required.",
                "",
                "Freeclaw uses a web OAuth callback endpoint:",
                "- `http://<PUBLIC_IP>:3000/v1/oauth/callback`",
                "",
                "You must use your server's public IP in Google Cloud redirect settings.",
                "",
                "## 1) Prerequisites",
                "- You have a Google account.",
                "- Your bot host has a public IP address.",
                "- Port `3000` is reachable from the internet (router/NAT/firewall/security group).",
                "- `timer-api` is running on the host where Discord bots run.",
                "",
                "Find your public IP (examples):",
                "- `curl -4 ifconfig.me`",
                "- `curl -4 https://api.ipify.org`",
                "",
                "In this guide, replace `<PUBLIC_IP>` with that value.",
                "",
                "## 2) Create a Google Cloud project",
                "1. Open Google Cloud Console: https://console.cloud.google.com/",
                "2. Create a new project (or choose an existing one).",
                "3. In that project, open `APIs & Services`.",
                "4. Enable required APIs:",
                "   - Gmail API (if you use `google_email_*` tools)",
                "   - Google Calendar API (if you use `google_calendar_*` tools)",
                "",
                "## 3) Configure OAuth consent screen",
                "1. Open `APIs & Services -> OAuth consent screen`.",
                "2. Choose `External` (typical for personal use).",
                "3. Fill app name/support email/developer email.",
                "4. Add scopes you need (examples below).",
                "5. Add your Google account as a test user while app is in testing.",
                "",
                "Recommended scopes:",
                "- `openid`",
                "- `email`",
                "- `https://www.googleapis.com/auth/gmail.readonly`",
                "- `https://www.googleapis.com/auth/calendar.readonly`",
                "",
                "If you want send/create actions, use broader scopes:",
                "- Gmail send: `https://www.googleapis.com/auth/gmail.send`",
                "- Calendar write: `https://www.googleapis.com/auth/calendar.events`",
                "",
                "## 4) Create OAuth client credentials (Web application)",
                "1. Open `APIs & Services -> Credentials`.",
                "2. Click `Create Credentials -> OAuth client ID`.",
                "3. Application type: `Web application`.",
                "4. Add Authorized redirect URI:",
                "   - `http://<PUBLIC_IP>:3000/v1/oauth/callback`",
                "5. Save, then copy:",
                "   - Client ID",
                "   - Client Secret",
                "",
                "Important:",
                "- Redirect URI must match exactly (scheme, host, port, path).",
                "- If you change IP/port/path, update both Google Cloud and `.env`.",
                "",
                "## 5) Set Freeclaw environment variables",
                "In the bot env file (`config/.env` or `config/agents/<name>/.env`), set:",
                "",
                "```dotenv",
                "FREECLAW_GOOGLE_CLIENT_ID=your-client-id.apps.googleusercontent.com",
                "FREECLAW_GOOGLE_CLIENT_SECRET=your-client-secret",
                "FREECLAW_GOOGLE_REDIRECT_URI=http://<PUBLIC_IP>:3000/v1/oauth/callback",
                "FREECLAW_GOOGLE_DEFAULT_SCOPES=https://www.googleapis.com/auth/calendar.readonly https://www.googleapis.com/auth/gmail.readonly openid email",
                "FREECLAW_GOOGLE_OAUTH_TIMEOUT_S=20.0",
                "FREECLAW_GOOGLE_CONNECT_EXPIRES_S=900",
                "```",
                "",
                "Notes:",
                "- Keep client secret private.",
                "- `FREECLAW_GOOGLE_DEFAULT_SCOPES` can be changed later.",
                "",
                "## 6) Run timer-api on public bind",
                "Freeclaw needs the callback endpoint reachable by Google.",
                "",
                "```bash",
                "python -m freeclaw timer-api --host 0.0.0.0 --port 3000",
                "```",
                "",
                "If you use `python -m freeclaw discord`, it can auto-start timer-api sidecar.",
                "Make sure sidecar port matches your redirect URI port.",
                "",
                "## 7) Link account from Discord",
                "1. In Discord: `/google connect`",
                "2. Open the authorization URL from the bot response.",
                "3. Approve access in browser.",
                "4. In Discord: `/google poll`",
                "5. Verify with `/google status`",
                "",
                "To unlink:",
                "- `/google disconnect`",
                "",
                "## 8) Troubleshooting",
                "- `redirect_uri_mismatch`: redirect URI in Google Cloud does not exactly match `.env` value.",
                "- `Google auth callback hit unknown state`: wrong memory DB or stale connect flow. Run `/google connect` again.",
                "- `connect expired`: run `/google connect` again (default expiry is 15 minutes).",
                "- Callback not reached: confirm public IP, open port 3000, and timer-api is running.",
                "",
                "## Security Checklist",
                "- Use a host firewall and only expose required ports.",
                "- Keep bot/project private when testing.",
                "- Rotate client secret if it is exposed.",
                "- Do not commit real client credentials into git.",
                "",
            ]
        )
        + "\n"
    )

